
spring:



  datasource:
    url: jdbc:postgresql://postgresql-account:5432/accountdb
    username: postgres
    password: damiane1997
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://postgresql-account:5432/accountdb
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: ACCOUNT-SERVICE
  cloud:
    config:
      enabled: false
#  config:
#    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


server:
  port: 8485

jwt:
  secret-key: OkvEZ85awEncAr2d3F4z2OTDHRZRyTJdGd0JSwSwSQo=